[package]
name = "imhonet_export"
version = "0.0.1"
authors = [ "Sergei Smirnov <ggrraay@gmail.com" ]

[dependencies]
hyper = "0.9"
rustc-serialize = "0.3"
log = "0.3"
env_logger = "0.3"
sxd-xpath = { git = "https://github.com/shepmaster/sxd-xpath.git" }
sxd-document = "0.2"